### ISSUE TITLE
Send preState in setStore?

### ISSUE THREAD

**Issue by hrahimi270** [ebrahimiaval/trim-redux#1]
Hi @ebrahimiaval.
It'll be useful if we can have `prevStore` as a parameter of `setStore` to use it as an [object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Syntax).
Currently, I have to get my store from `getStore` and pass it as literal to my `setStore`. like this:
![image](https://user-images.githubusercontent.com/38007163/58763104-3d204d00-856c-11e9-920a-c0db272aeccc.png)

**Comment by ebrahimiaval** [comment]
yes, It'll be useful but we trying to be like state of React Component. if you can do this, fork and send pull request.
